import Head from "next/head"
import Header from "../components/Header"
import { getSession } from "next-auth/react"
import Login from "../components/Login"
import Sidebar from "../components/Sidebar"
import Feed from "../components/Feed"
import Widgets from "../components/Widgets"
import { collection, getDoc, getDocs, orderBy, query } from "firebase/firestore"
import { db } from "../firebase"

export default function Home({ session, posts }) {
  if (!session) return <Login />
  return (
    <div className="h-screen bg-gray-100 overflow-hidden">
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <main className="flex">
        {/* Sidebar */}
        <Sidebar />
        {/* Feed */}
        <Feed posts={posts} />
        {/* Widgets */}
        <Widgets />
      </main>
    </div>
  )
}

export async function getServerSideProps(context) {
  // Get the User
  const session = await getSession(context)
  const posts = await getDocs(query(collection(db, 'posts'), orderBy('timestamp', 'desc')))

  const docs = posts.docs.map(post => ({
    id: post.id,
    ...post.data(),
    timestamp: null
  }))
  return {
    props: {
      session,
      posts: docs
    }
  }
}
